### ISSUE TITLE
Don't treat non-exist import module  as a error if there is no any effective reference to this import module in current module

### ISSUE THREAD

**Issue by lllyfeng** [netmod-wg/yang-next#114]
for instance,

```
module import-module {
  prefix im;
 //definitions 
   leaf bar {
     type boolean;
   }
}

module cur-module {
 prefix cur;
 import import-module {
    prefix im;  
} 

  leaf foo {
    type string;
    when "/im:bar";
  }
}

module dev-module {
  import cur-module {
    prefix cur;
  }
   deviation "cur:foo" {
       deviate not-supported;
  }
}
```

In this example, module cur-module has no leaf foo in effect, So actually, the import-module is no useful for cur-module, but cur-module MUST be provided to ensure a successful compliation. I suggest it should not be treated as error when a import module is actually no useful.

**Comment by abierman** [comment]
Do not support this change.
This is not possible to implement since the deviation module is not known when the main module is parsed.

A related issue:
- what if the imported module is not found but the prefix is not used in the importing module?

If the prefix is used in the importing module then the imported module MUST be found.

More Discuss: complexity: high, bc: medium, importance: low

**Comment by janlindblad** [comment]
Agree with Andy this is a non-implementable idea.
