### ISSUE TITLE
Add validation-rules-stmt to identify YANG validation scope

### ISSUE THREAD

**Issue by abierman** [netmod-wg/yang-next#137]
There are some use-cases where full YANG validation is not possible.
This is sometimes called the "offline validation problem".

Even though YANG says <running> MUST be valid, this is not always the case.
There may be other data validation contexts to consider besides config=true.

- config=true XPath references operational data
- config contains templates or other "pre-processing" data

### validation-rules-stmt

```
validation-rules  "strict" / "relaxed" / "off" ;
```

- If full RFC validation is expected and possible, the default value 'strict' is used
-  If full or RFC validation is expected and possible only if multiple datastores 
   are available and correct, or mandatory within NP-container, the value 'relaxed' is used
-  If YANG validation is suppressed for the subtree, then the value 'off' is used

Case 1) Set to off for the proprietary templates

```
container templates {
   validation-rules off;
   // ...
}
```

Case 2) Set to relaxed for a multiple datastore reference

```
container some-feature {
   when "/some/operational/installed-flag";
   validation-rules relaxed;
   // ...
}
```
Case 3) Set to relaxed for nested mandatory

```
container connections {
     validation-rules relaxed;
     uses some-grouping-with-mandatory-leaf;
}
````

The validation-rules may not apply to the entire subtree of the object containing the statement.
Details of nested statement usage need to be clarified.

**Comment by BalazsLengyel** [comment]
Not fully clear. 
YANG model validation or yang instance data validation? I assume yang instance data.

**Comment by janlindblad** [comment]
We need to tread carefully here, IMO; this is dragon territory. Since we are talking about automation here, where a client (controller) is managing a set of servers (devices, lower level controllers), the key requirement is that the controller has full knowledge and control over its subjects' configuration (marching orders), or at least the parts of it that the controller cares about. If there are config aspects in the controlled servers the controller can't know about, automation use cases will suffer.

**Comment by kwatsen** [comment]
The examples are not compelling for me.

Case 1: the template should be expanded in <intended>, which is subject to validation

Case 2: CF must not ref CT is wise.  I think what is desired is actually CT-in-running refs a CT-in-system.

Case 3: I think that all containers should be treated like a presence container, so that mandatory descendants re only mandatory when the container exists.  If descendants are truly required, a `must` expression can be used.

**Comment by kwatsen** [comment]
Closing per meeting on Oct 24
