### ISSUE TITLE
Add 'clone' statement

### ISSUE THREAD

**Issue by abierman** [netmod-wg/yang-next#31]
It is not possible or desirable to define every data structure as a grouping
in case it needs to be reused in the future.

Possible solution: add a "clone" data-def-stmt that is similar to "uses"
except an existing data node is used instead of a grouping

  clone "/if:interfaces/if:interface" {
     // same sub-statements as uses, e.g.
     refine ....
     augment ....
  }

**Comment by schoenw** [comment]
This may be widely misused and often you need to make changes to what was cloned.

**Comment by abierman** [comment]
This would work exactly like grouping today except it would make a copy
of an existing schema node. It might be abused more or the same as grouping

IMO grouping is now being abused because there are so many single-use groupings
which are hard to read.

But clone may be too complicated to add

It would be hard to detect clone loops especially if clone was allowed in a grouping

**Comment by schoenw** [comment]
A grouping requires that someone thinks about reuse while writing the definition. This is not as easy as it sounds since you have to be careful with description statements (that need to make sense in various contexts) and of course any must or when constraints.

With clone, everybody can clone everything and I would not be surprised to see acm-interfaces { import ietf-interfaces; clone if:interfaces; } (which some people already do today with cut'n'paste - so one could argue that clone is better than cut'n'paste but I think it is still the wrong trajectory).

That said, it could be that clone would reduce the number of groupings we see that are written just in case reuse could be useful. But then it might also be that many groupings we see are just an attempt to have more modular definitions and reuse is not really the prime goal of using a grouping.

I guess I consider this a low priority proposal unless people can convince me that we did run into a significant number of situations where reuse was _necessary_ and _meaningful_ but the author of the data model did not design groupings for reuse and the definitions were self-contained enough to be reused without tweaking them.

**Comment by abierman** [comment]
Withdrawing this proposal since too many issues introduced

**Comment by kwatsen** [comment]
Closed during Feb 6 Virtual Interim meeting.
